In [ ]:
%load_ext autoreload
%autoreload 2
import pyarrow as pa
import sys
import os
sys.path.insert(0, os.path.abspath('..'))
from src.data_loader import load_data
from src.vector_store import create_chroma_collection,add_embeddings
from src.preprocessing import create_stratified_sample,chunk_dataset,chunk_text
from src.embedding import (load_embedding_model,generate_embeddings)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
filtered_complaints = load_data("../data/processed/filtered_complaints.csv")

Dataset loaded successfully.
Rows: 549585
Columns: 20

# Stratified Sampling

In [4]:
sample_df = create_stratified_sample(filtered_complaints, sample_size=10000)

print(sample_df.shape)

(10000, 20)

In [5]:
distribution = (
    sample_df["Product Category"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(distribution)

Product Category
Credit Card        34.45
Savings Account    25.53
Personal Loan      22.06
Money Transfer     17.96
Name: proportion, dtype: float64

In [6]:
sample_df["Product Category"].value_counts()

Product Category
Credit Card        3445
Savings Account    2553
Personal Loan      2206
Money Transfer     1796
Name: count, dtype: int64

In [7]:
sample_df.to_csv(
    "../data/processed/filtered_complaints_sample.csv",
    index=False
)

# Chunking

In [8]:
chunked_df = chunk_dataset(
    sample_df,
    chunk_size=500,
    chunk_overlap=50
)

print(chunked_df.shape)

chunked_df.head()

(29099, 23)

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,...,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,word_count,Product Category,chunk,chunk_index,total_chunks
0,2025-02-12,Checking or savings account,Other banking product or service,Managing an account,Funds not handled or disbursed as instructed,my account was closed from xxxx and at the tim...,NaN,"Block, Inc.",TX,77583,...,2025-02-12,Closed with explanation,Yes,NaN,12072607,180,Savings Account,my account was closed from xxxx and at the tim...,0,2
0,2025-02-12,Checking or savings account,Other banking product or service,Managing an account,Funds not handled or disbursed as instructed,my account was closed from xxxx and at the tim...,NaN,"Block, Inc.",TX,77583,...,2025-02-12,Closed with explanation,Yes,NaN,12072607,180,Savings Account,can trace my funds and return them to me i hav...,1,2
1,2025-01-20,"Money transfer, virtual currency, or money ser...",Domestic (US) money transfer,Other transaction problem,NaN,i am filing a complaint against cash app block...,NaN,"Block, Inc.",CO,80205,...,2025-01-20,Closed with explanation,Yes,NaN,11614309,102,Money Transfer,i am filing a complaint against cash app block...,0,2
1,2025-01-20,"Money transfer, virtual currency, or money ser...",Domestic (US) money transfer,Other transaction problem,NaN,i am filing a complaint against cash app block...,NaN,"Block, Inc.",CO,80205,...,2025-01-20,Closed with explanation,Yes,NaN,11614309,102,Money Transfer,under the electronic fund transfer act efta an...,1,2
2,2025-03-13,"Money transfer, virtual currency, or money ser...",Mobile or digital wallet,Unauthorized transactions or other transaction...,NaN,cash app respond is insane said they couldnt g...,NaN,"Block, Inc.",VA,237XX,...,2025-03-13,Closed with explanation,Yes,NaN,12457083,12,Money Transfer,cash app respond is insane said they couldnt g...,0,1

In [10]:
configs = [
    (300,30),
    (500,50),
    (700,100)
]

for chunk_size, overlap in configs:

    chunked = chunk_dataset(
        sample_df,
        chunk_size=chunk_size,
        chunk_overlap=overlap
    )

    print(f"\nChunk size: {chunk_size}")
    print(f"Overlap: {overlap}")
    print(f"Total chunks: {len(chunked)}")

    avg_length = chunked["chunk"].str.len().mean()

    print(f"Average chunk length: {avg_length:.1f}")

KeyboardInterrupt:

In [13]:
text = sample_df.iloc[0]["Consumer complaint narrative"]

for size, overlap in [(300,30),(500,50),(600,70),(700,100)]:

    chunks = chunk_text(
        text,
        chunk_size=size,
        chunk_overlap=overlap
    )

    print("="*80)
    print(size, overlap)

    for i,c in enumerate(chunks[:3]):
        print(f"\nChunk {i+1}\n")
        print(c)

================================================================================
300 30

Chunk 1

my account was closed from xxxx and at the time i had several ach items that were supposed to be returned to my cashapp account that never were i wanted to reach back out to see where my funds actually went before i file my complaint with the xxxx and the fdic in regards to my missing funds i have

Chunk 2

to my missing funds i have been waiting on over 2000 00 i contacted the bank and they stated the money was sent back to cashapp so i contacted cashapp with the trace number so they can trace my funds and return them to me i have been more than patient trying to track down my money and no one wants

Chunk 3

my money and no one wants to be held accountable when my funds were returned to the account cashapp could have simply mailed me a check but they didn t do that and now my money seems to be lost in the wind the has caused me financial distress and i need to know where my money is because it has been
================================================================================
500 50

Chunk 1

my account was closed from xxxx and at the time i had several ach items that were supposed to be returned to my cashapp account that never were i wanted to reach back out to see where my funds actually went before i file my complaint with the xxxx and the fdic in regards to my missing funds i have been waiting on over 2000 00 i contacted the bank and they stated the money was sent back to cashapp so i contacted cashapp with the trace number so they can trace my funds and return them to me i have

Chunk 2

can trace my funds and return them to me i have been more than patient trying to track down my money and no one wants to be held accountable when my funds were returned to the account cashapp could have simply mailed me a check but they didn t do that and now my money seems to be lost in the wind the has caused me financial distress and i need to know where my money is because it has been 3 months and by law they need to return my money
================================================================================
600 70

Chunk 1

my account was closed from xxxx and at the time i had several ach items that were supposed to be returned to my cashapp account that never were i wanted to reach back out to see where my funds actually went before i file my complaint with the xxxx and the fdic in regards to my missing funds i have been waiting on over 2000 00 i contacted the bank and they stated the money was sent back to cashapp so i contacted cashapp with the trace number so they can trace my funds and return them to me i have been more than patient trying to track down my money and no one wants to be held accountable when

Chunk 2

to track down my money and no one wants to be held accountable when my funds were returned to the account cashapp could have simply mailed me a check but they didn t do that and now my money seems to be lost in the wind the has caused me financial distress and i need to know where my money is because it has been 3 months and by law they need to return my money
================================================================================
700 100

Chunk 1

my account was closed from xxxx and at the time i had several ach items that were supposed to be returned to my cashapp account that never were i wanted to reach back out to see where my funds actually went before i file my complaint with the xxxx and the fdic in regards to my missing funds i have been waiting on over 2000 00 i contacted the bank and they stated the money was sent back to cashapp so i contacted cashapp with the trace number so they can trace my funds and return them to me i have been more than patient trying to track down my money and no one wants to be held accountable when my funds were returned to the account cashapp could have simply mailed me a check but they didn t do

Chunk 2

funds were returned to the account cashapp could have simply mailed me a check but they didn t do that and now my money seems to be lost in the wind the has caused me financial distress and i need to know where my money is because it has been 3 months and by law they need to return my money

# Generate Embeddings

In [11]:

model = load_embedding_model()

chunked_df = generate_embeddings(
    chunked_df,
    model
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loaded embedding model: sentence-transformers/all-MiniLM-L6-v2

Batches:   0%|          | 0/455 [00:00<?, ?it/s]

In [12]:
chunked_df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,...,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,word_count,Product Category,chunk,chunk_index,total_chunks,embedding
0,2025-02-12,Checking or savings account,Other banking product or service,Managing an account,Funds not handled or disbursed as instructed,my account was closed from xxxx and at the tim...,NaN,"Block, Inc.",TX,77583,...,Closed with explanation,Yes,NaN,12072607,180,Savings Account,my account was closed from xxxx and at the tim...,0,2,"[0.013290705159306526, -0.012922031804919243, ..."
0,2025-02-12,Checking or savings account,Other banking product or service,Managing an account,Funds not handled or disbursed as instructed,my account was closed from xxxx and at the tim...,NaN,"Block, Inc.",TX,77583,...,Closed with explanation,Yes,NaN,12072607,180,Savings Account,can trace my funds and return them to me i hav...,1,2,"[0.030819974839687347, -0.01960556022822857, -..."
1,2025-01-20,"Money transfer, virtual currency, or money ser...",Domestic (US) money transfer,Other transaction problem,NaN,i am filing a complaint against cash app block...,NaN,"Block, Inc.",CO,80205,...,Closed with explanation,Yes,NaN,11614309,102,Money Transfer,i am filing a complaint against cash app block...,0,2,"[-0.12191501259803772, 0.054789312183856964, 0..."
1,2025-01-20,"Money transfer, virtual currency, or money ser...",Domestic (US) money transfer,Other transaction problem,NaN,i am filing a complaint against cash app block...,NaN,"Block, Inc.",CO,80205,...,Closed with explanation,Yes,NaN,11614309,102,Money Transfer,under the electronic fund transfer act efta an...,1,2,"[0.01816040836274624, 0.02550520747900009, -0...."
2,2025-03-13,"Money transfer, virtual currency, or money ser...",Mobile or digital wallet,Unauthorized transactions or other transaction...,NaN,cash app respond is insane said they couldnt g...,NaN,"Block, Inc.",VA,237XX,...,Closed with explanation,Yes,NaN,12457083,12,Money Transfer,cash app respond is insane said they couldnt g...,0,1,"[-0.09607723355293274, 0.017643800005316734, 0..."

In [13]:
embedding = chunked_df.iloc[0]["embedding"]

print(len(embedding))

384

In [14]:
chunked_df.to_parquet(
    "../data/processed/complaint_embeddings.parquet",
    index=False
)

In [19]:
print(chunked_df.index.is_unique)

False

In [20]:
chunked_df = chunked_df.reset_index(drop=True)

# Build Vector Database

In [21]:
collection = create_chroma_collection()

add_embeddings(
    collection,
    chunked_df
)

Indexing Chunks:   0%|          | 0/6 [00:00<?, ?it/s]

Successfully indexed 29,099 chunks.

Collection(name=complaints)

In [23]:
collection.peek()

{'ids': ['chunk_0',
  'chunk_1',
  'chunk_2',
  'chunk_3',
  'chunk_4',
  'chunk_5',
  'chunk_6',
  'chunk_7',
  'chunk_8',
  'chunk_9'],
 'embeddings': array([[ 0.01329071, -0.01292203, -0.0542267 , ..., -0.05230036,
         -0.00762858,  0.00726825],
        [ 0.03081997, -0.01960556, -0.05421557, ..., -0.04685511,
          0.05140719,  0.02350499],
        [-0.12191501,  0.05478931,  0.02025292, ..., -0.03437499,
          0.06055311,  0.05405391],
        ...,
        [ 0.05693175,  0.03280631, -0.00580777, ..., -0.03125641,
          0.03252798, -0.05417583],
        [ 0.03694901, -0.07664038,  0.00065599, ..., -0.05211463,
         -0.11491901, -0.04376294],
        [-0.01256569, -0.00941585,  0.04053326, ..., -0.0736514 ,
         -0.01445731, -0.04286427]], shape=(10, 384)),
 'documents': ['my account was closed from xxxx and at the time i had several ach items that were supposed to be returned to my cashapp account that never were i wanted to reach back out to see where my funds actually went before i file my complaint with the xxxx and the fdic in regards to my missing funds i have been waiting on over 2000 00 i contacted the bank and they stated the money was sent back to cashapp so i contacted cashapp with the trace number so they can trace my funds and return them to me i have',
  'can trace my funds and return them to me i have been more than patient trying to track down my money and no one wants to be held accountable when my funds were returned to the account cashapp could have simply mailed me a check but they didn t do that and now my money seems to be lost in the wind the has caused me financial distress and i need to know where my money is because it has been 3 months and by law they need to return my money',
  'i am filing a complaint against cash app block inc due to inadequate customer service and unfair practices which violate the consumer financial protection act cfpa specifically cash app failed to take timely and effective measures to prevent and address fraud on their platform leaving my account vulnerable and unprotected furthermore their dispute resolution process was unfair and deceptive as they did not comply with error resolution requirements under the electronic fund transfer act efta and',
  'under the electronic fund transfer act efta and regulation e these actions have caused significant inconvenience and financial loss and i seek appropriate redress for these violations',
  'cash app respond is insane said they couldnt give my money back',
  'xx xx 2022 i called indigo credit card company because i receive a credit card that i did not apply for this year in the mail i did not want the card therefor i did not activate a week later i receive a bill in the mail i called to let them know that i do not wish to have this card this is why i did not activate it and that i did not apply for the card recently i was told by the representative that once i request for the card its automatically my card and that i am responsibility to pay i asked',
  'card and that i am responsibility to pay i asked to speak to someone in charge which she told me was not available and that i will get a call back and i never did and the bill is due today a week after i received the card that i do not wish to activate',
  'i took over as the xxxx for a non profit corporation that banks with citizens the prior xxxx arranged a meeting with the branch xxxx to remove the prior xxxx from our accounts at citizens and add me as the xxxx of the accounts we have xxxx savings accounts and xxxx checking accounts the meeting at the branch took place on xx xx year at the citizens bank xxxx xxxxxx xx xxxxwe had the officers of the non profit meet with the branch xxxx and we signed documents etc i was told by the branch xxxx',
  'documents etc i was told by the branch xxxx that administrative control was transferred to my name and that i should try logging in to the accounts when i got home we left the branch and i was unable to register for online access using the citizens app i waited until the following week to follow up with the branch i called and was told the branch xxxx was on vacation over the course of the next week i followed up numerous times i asked for the branch xxxx to call me but never heard from him',
  'branch xxxx to call me but never heard from him again i sent at least xxxx emails and requested several times to the branch employees to have the branch xxxx contact me but i never heard from him xxxx of the branch staff reset the password linked to the treasurer s email address which i had access to and i was able to login as the xxxx on xx xx year the old xxxx s contact information was still listed on the account and the account was still tied to his cell phone number i spoke to branch staff'],
 'uris': None,
 'included': ['metadatas', 'documents', 'embeddings'],
 'data': None,
 'metadatas': [{'date_received': '2025-02-12',
   'state': 'TX',
   'complaint_id': '12072607',
   'issue': 'Managing an account',
   'chunk_index': 0,
   'product_category': 'Savings Account',
   'sub_issue': 'Funds not handled or disbursed as instructed',
   'company': 'Block, Inc.',
   'total_chunks': 2,
   'product': 'Checking or savings account'},
  {'issue': 'Managing an account',
   'date_received': '2025-02-12',
   'company': 'Block, Inc.',
   'product_category': 'Savings Account',
   'sub_issue': 'Funds not handled or disbursed as instructed',
   'state': 'TX',
   'product': 'Checking or savings account',
   'complaint_id': '12072607',
   'chunk_index': 1,
   'total_chunks': 2},
  {'issue': 'Other transaction problem',
   'company': 'Block, Inc.',
   'product_category': 'Money Transfer',
   'complaint_id': '11614309',
   'date_received': '2025-01-20',
   'chunk_index': 0,
   'product': 'Money transfer, virtual currency, or money service',
   'state': 'CO',
   'total_chunks': 2},
  {'total_chunks': 2,
   'product': 'Money transfer, virtual currency, or money service',
   'issue': 'Other transaction problem',
   'complaint_id': '11614309',
   'state': 'CO',
   'chunk_index': 1,
   'company': 'Block, Inc.',
   'date_received': '2025-01-20',
   'product_category': 'Money Transfer'},
  {'company': 'Block, Inc.',
   'chunk_index': 0,
   'issue': 'Unauthorized transactions or other transaction problem',
   'product': 'Money transfer, virtual currency, or money service',
   'product_category': 'Money Transfer',
   'date_received': '2025-03-13',
   'complaint_id': '12457083',
   'state': 'VA',
   'total_chunks': 1},
  {'product_category': 'Credit Card',
   'company': 'CLGF Holdco 1, LLC',
   'sub_issue': 'Sent card you never applied for',
   'product': 'Credit card or prepaid card',
   'complaint_id': '5363996',
   'date_received': '2022-03-24',
   'issue': 'Getting a credit card',
   'state': 'FL',
   'total_chunks': 2,
   'chunk_index': 0},
  {'issue': 'Getting a credit card',
   'product': 'Credit card or prepaid card',
   'sub_issue': 'Sent card you never applied for',
   'complaint_id': '5363996',
   'date_received': '2022-03-24',
   'total_chunks': 2,
   'chunk_index': 1,
   'product_category': 'Credit Card',
   'company': 'CLGF Holdco 1, LLC',
   'state': 'FL'},
  {'complaint_id': '9829279',
   'total_chunks': 4,
   'product': 'Checking or savings account',
   'sub_issue': 'Problem accessing account',
   'product_category': 'Savings Account',
   'state': 'NJ',
   'chunk_index': 0,
   'company': 'CITIZENS FINANCIAL GROUP, INC.',
   'date_received': '2024-08-16',
   'issue': 'Managing an account'},
  {'total_chunks': 4,
   'issue': 'Managing an account',
   'product_category': 'Savings Account',
   'chunk_index': 1,
   'complaint_id': '9829279',
   'product': 'Checking or savings account',
   'date_received': '2024-08-16',
   'state': 'NJ',
   'company': 'CITIZENS FINANCIAL GROUP, INC.',
   'sub_issue': 'Problem accessing account'},
  {'total_chunks': 4,
   'state': 'NJ',
   'date_received': '2024-08-16',
   'company': 'CITIZENS FINANCIAL GROUP, INC.',
   'sub_issue': 'Problem accessing account',
   'issue': 'Managing an account',
   'chunk_index': 2,
   'product': 'Checking or savings account',
   'product_category': 'Savings Account',
   'complaint_id': '9829279'}]}